DROP TRIGGER IF EXISTS t_delete_user_idx ON T_USER;
DROP TRIGGER IF EXISTS t_update_user_idx_insert ON T_USER;
DROP TRIGGER IF EXISTS t_update_user_idx_update ON T_USER;

DROP TABLE IF EXISTS T_USER_IDX CASCADE;
DROP TABLE IF EXISTS T_USER CASCADE;
