GRANT ALL ON SCHEMA public TO bblvertx;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bblvertx;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO bblvertx;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO bblvertx;